#!/usr/bin/perl

use 5.12.2;
use warnings;

my ($SRC_DIR) = @ARGV;

`mkdir -p dest`;
my $PWD = `pwd`;
chomp $PWD;
my $DEST_DIR = "$PWD/dest";
say $DEST_DIR;

chdir $SRC_DIR;

my @git_files = `git ls-files`;

my $re_blame = /^[a-f0-9]+\s+\(<([^>]+)[^)]+\)\s(.*)$/;
#99594011 (<malcolm.tredinnick@gmail.com> 2008-08-09 14:40:51 +0000  1) Copyright (c) Dj...

my $count = 0;
my $total = scalar @git_files;

foreach my $file (@git_files) {
    chomp $file;
    next if -B $file;

    my $dir = `dirname $file`;
    my @blame = `git blame -ew $file`;
    my @out = ();
    foreach my $line (@blame) {
        chomp $line;

        $line =~ /^[a-f0-9]+\s+\(<([^>]+)[^)]+\)\s(.*)$/;
        if ($1) {
            push @out, "<tr><td>$1</td><td>$2</td></tr>";
        }
    }
    `mkdir -p $DEST_DIR/$dir`;
    open(my $fh, '>', "$DEST_DIR/$file") or die "cant open";
    print $fh join '', ('<table>', @out, '</table>');
    close $fh;

    print "processed $count/$total\r";
    $count +=1;
}
print "\n";
